theme: jekyll-theme-hacker
name: R4yquazID
description: WhiteHat & Datacenter Engineer
avatar: https://raw.githubusercontent.com/RayquazID/rayquazid.github.io/master/images/28209d1b9c49c25201a8d53c36cd1b3b.jpg

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:

